# Generated by Django 2.0 on 2018-05-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180525_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_images',
            field=models.ImageField(default=None, upload_to='<django.db.models.fields.CharField>/', verbose_name='配图'),
            preserve_default=False,
        ),
    ]
