# Generated by Django 2.0 on 2018-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_blog_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_images',
            field=models.ImageField(upload_to='uploads/', verbose_name='配图'),
        ),
    ]
