# Generated by Django 2.0 on 2018-05-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180527_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_images',
            field=models.ImageField(upload_to='uploads', verbose_name='配图'),
        ),
    ]
