# Generated by Django 2.0 on 2018-05-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180527_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_images',
            field=models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='配图'),
        ),
    ]
