# Generated by Django 2.0 on 2018-05-27 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180527_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_contet',
            new_name='blog_content',
        ),
    ]
